# Generated by Django 3.2.5 on 2021-07-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_weekday_9A_6P', models.FloatField(verbose_name='R_MF_9A_6P')),
                ('rate_weekday_6P_10P', models.FloatField(verbose_name='R_MF_6P_10')),
                ('rate_sat_9A_6P', models.FloatField(verbose_name='R_SA_9A_6P')),
                ('rate_sat_6P_10P', models.FloatField(verbose_name='R_SA_6P_10')),
                ('rate_sun_9A_6P', models.FloatField(verbose_name='R_SU_9A_6P')),
                ('rate_sun_6P_10P', models.FloatField(verbose_name='R_SU_6P_10')),
                ('time_weekday_9A_6P', models.FloatField(verbose_name='T_MF_9A_6P')),
                ('time_weekday_6P_10P', models.FloatField(verbose_name='T_MF_6P_10')),
                ('time_sat_9A_6P', models.FloatField(verbose_name='T_SA_9A_6P')),
                ('time_sat_6P_10P', models.FloatField(verbose_name='T_SA_6P_10')),
                ('time_sun_9A_6P', models.FloatField(verbose_name='T_SU_9A_6P')),
                ('time_sun_6P_10P', models.FloatField(verbose_name='T_SU_6P_10')),
                ('credit_card', models.BooleanField(verbose_name='CREDITCARD')),
                ('pay_phone', models.IntegerField(verbose_name='PAY_PHONE')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('long', models.FloatField(verbose_name='Longitude')),
                ('location', models.CharField(max_length=140, verbose_name='Geo Local Area')),
                ('meter_id', models.IntegerField(verbose_name='METERID')),
            ],
        ),
    ]
