# Generated by Django 3.2.5 on 2021-07-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkMap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='id',
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='METERID'),
        ),
    ]
